DJANGO/Django site/Test1/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from .views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", home),
    path("home/testapp/", include("apps.testapp.urls")),
    path("home/polls/", include("apps.polls.urls")),
    path("home/polls2/", include("apps.polls2.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
]

DJANGO/Django site/apps/polls/urls.py
from django.urls import path
from .views import *

# URL CONF
app_name = "polls"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("<int:question_id>/", detail, name="detail"),
    path("<int:question_id>/results/", results, name="results"),
    path("<int:question_id>/vote/", vote, name="vote"),
]

DJANGO/Django site/apps/polls2/urls.py
from django.urls import path

from . import views

app_name = "polls2"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

DJANGO/Django site/apps/testapp/urls.py
from django.urls import path

from .views import *


# URLConf module
urlpatterns = [
    path("", room, name="room"),
    path("<str:id>/", room_detail, name="room_detail"),
]

DJANGO/Django site/apps/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.


# * Here each model is child of class django.db.models.Model. thats why we put models.Model inside the bracket of class.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def was_published_recently(self):
        return (
            timezone.now()
            >= self.pub_date
            >= timezone.now() - datetime.timedelta(days=1)
        )

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Marks(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    total_marks = models.IntegerField(default=100)
    pass_marks = models.IntegerField(default=40)

    def __str__(self):
        return str(self.total_marks)

DJANGO/Django site/apps/polls2/models.py
from django.db import models


# Create your models here.


# * Here each model is child of class django.db.models.Model. thats why we put models.Model inside the bracket of class.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Marks(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    total_marks = models.IntegerField(default=100)
    pass_marks = models.IntegerField(default=40)

    def __str__(self):
        return str(self.total_marks)

DJANGO/Django site/Test1/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html")

DJANGO/Django site/apps/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# displays the latest 5 poll questions in the system,

"""def index(request):
    question_list = Question.objects.order_by("-pub_date")[:5]
    return render(request, "polls/index.html", {"questions": question_list})"""

# Using class based generic views


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "questions"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]


def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    question = get_object_or_404(Question, pk=question_id)  # shortcut
    return render(request, "polls/detail.html", {"question": question})


# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     choice_id = request.POST["option"]
#     selected_choice = question.choice_set.get(pk=choice_id)
#     selected_choice.votes = F("votes") + 1
#     selected_choice.save()


#     return HttpResponseRedirect(reverse("polls:results", args=(question_id)))
def vote(request, question_id):
    print("everything al right")
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
        # return render(request, "polls/results.html", {"question": question})


def results(request, question_id):
    print("this is ", request.method)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

    # here, we use post->redirect->get (PRG) pattern.

DJANGO/Django site/apps/polls2/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import *
from django.db.models import F


class IndexView(generic.ListView):
    template_name = "polls2/index.html"
    context_object_name = "questions"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls2/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls2/results.html"


def vote(request, question_id):
    print("everything al right")
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls2:results", args=(question.id,)))
        # return render(request, "polls2/results.html", {"question": question})

DJANGO/Django site/apps/testapp/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.


def room(request):
    context = {
        "rooms": [
            {"id": 1, "msg": "Lets learn python"},
            {"id": 2, "msg": "Design database with me"},
            {"id": 3, "msg": "Analysis data with me"},
        ]
    }
    return render(request, "testapp/room.html", context)


rooms_detail = [
    {"id": 1, "owner": "basnet", "location": "right corner"},
    {"id": 2, "owner": "hari", "location": "middle"},
    {"id": 3, "owner": "prabesh", "location": "left corner"},
]


def room_detail(request, id):

    for room in rooms_detail:
        if room["id"] == int(id):
            return render(request, "testapp/room_detail.html", room)
    return HttpResponse("room not found")

DJANGO/Django site/templates/home.html
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>

<body>
    <h1>This is testing of my Django understanding</h1> <br>

    <div>
        {% block content %}

        {% endblock %}
    </div>
</body>

</html>

DJANGO/Django site/templates/navbar.html
<a href="#">
    <h1>LOGO</h1>
</a>
<hr>

DJANGO/Django site/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>detail</title>
</head>

<body>
    <h1> The question Details</h1>
    <p>
        {{ question.id }}-> {{ question.question_text }} <br> {{ question.pub_date }}
    </p>
    <h2>Choices under this question</h2>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} - {{ choice.votes}} </li>
        {% endfor %}
    </ul>
    <h3>Marks under this question</h3>
    {% for m in question.marks_set.all %}
    marks - {{ m }}
    {% endfor %}
    <!-- form -->
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>

</html>

DJANGO/Django site/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>

<body>
    <h1>this is index page</h1>
    {% for q in questions %}

    <li><a href="{% url 'polls:detail' q.id %}">{{ q.id }} -> {{ q.question_text }} {{ q.pub_date }}</li></a>
    {% endfor %}


</body>

</html>

DJANGO/Django site/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>result</title>
</head>

<body>
    <!-- <h1>Vote succesfull. This is result of question {{ question.id}}</h1>
    {% for choice in question.choice_set.all %}
    <p>{{ choice.choice_text }} --- {{ choice.votes }}</p>
    {% endfor %} -->
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>

</html>

DJANGO/Django site/templates/testapp/room.html
{% extends 'home.html' %}
{% block content %}

<h1>this is room template</h1> <br>

{% for r in rooms %}
<div> Room No = {{r.id}} -- <a href="{{r.id}}">{{r.msg}}</a> </div>
{% endfor %}
{% endblock %}

DJANGO/Django site/templates/testapp/room_detail.html
{% extends 'home.html' %}
{% block content %}
<div>
    <h1>More about room </h1>
    Room No : {{id}} <br>
    Room Owner : {{owner}} <br>
    Room Location: {{location}}
</div>
{% endblock %}